name: Build Android

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build ionic app & copy assets
        run: ionic capacitor build android --no-open --prod

      - name: Generate the Android APK
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Save release bundle as artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: app-release
          path: ${{ github.workspace }}/android/app/build/outputs/apk/debug/app-debug.apk
